import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/navbar";
import Footer from "@/components/footer";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";

const urbanist = Urbanist({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Aromas de Café",
  description: "¡Bienvenido a Aromas de Café!",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={urbanist.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >


          <Navbar />
          {children}
          <Toaster />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}

//  import type { Metadata } from "next";
//  import { Urbanist } from "next/font/google";
//  import "./globals.css";
//  import Navbar from "@/components/ui/navbar";
//  import Footer from "@/components/footer";
//  import { ThemeProvider } from "@/components/theme-provider";
//  const urbanist = Urbanist({ subsets: ["latin"] });
//  export const metadata: Metadata = {
//    title: "Fabian Ecommerce",
//    description: "Generated by create next app Ecommerce",
//  };
//  export default function RootLayout({
//    children,
//  }: Readonly<{
//    children: React.ReactNode;
//  }>) {
//    return (
//      <html lang="en">
//        <body className={`${urbanist} antialiased`}>
//          <ThemeProvider
//            attribute="class"
//            defaultTheme="system"
//            enableSystem
//            disableTransitionOnChange
//          >
//            <Navbar />
//            {children}
//            <Footer />
//            </ThemeProvider>
//        </body>
//      </html>
//    );
//  }